[FIX] TypeError on LambdaClient(transport=...)
TypeError: __init__() got multiple values for keyword argument 'transport'

Because it has `get()`ing the 'transport' keyword, instead of `pop()`ing it.