Allow `extra` to be None in breadcrumbs processing
Sometimes, `extra` is passed in as a default parameter of another
function and can therefore be `None`. This fixes:

	Traceback (most recent call last):
	  File "raven/breadcrumbs.py", line 77, in get_buffer
		processor(payload)
	  File "raven/breadcrumbs.py", line 143, in processor
		data_value.update(extra)
	TypeError: 'NoneType' object is not iterable